# Random Forest

In [1]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn import datasets

# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

# Select your features (columns)

In [4]:
# Set features. This will also be used as your x values.
selected_features = df[['koi_fpflag_nt','koi_fpflag_ss','koi_fpflag_co','koi_fpflag_ec',
                        'koi_period','koi_period_err1','koi_period_err2',
                        'koi_time0bk','koi_time0bk_err1','koi_time0bk_err2',
                        'koi_impact','koi_impact_err1','koi_impact_err2',
                        'koi_duration','koi_duration_err1','koi_duration_err2',
                        'koi_depth','koi_depth_err1','koi_depth_err2',
                        'koi_prad','koi_prad_err1','koi_prad_err2',
                        'koi_teq','koi_insol','koi_insol_err1','koi_insol_err2',
                        'koi_model_snr','koi_steff','koi_steff_err1','koi_steff_err2',
                        'koi_slogg','koi_slogg_err1','koi_slogg_err2',
                        'koi_srad','koi_srad_err1','koi_srad_err2',
                        'ra','dec','koi_kepmag']]

In [5]:
selected_features.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0              0              0              0              0   54.418383   
1              0              1              0              0   19.899140   
2              0              1              0              0    1.736952   
3              0              0              0              0    2.525592   
4              0              0              0              0    4.134435   

   koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0     2.479000e-04    -2.479000e-04   162.513840          0.003520   
1     1.490000e-05    -1.490000e-05   175.850252          0.000581   
2     2.630000e-07    -2.630000e-07   170.307565          0.000115   
3     3.760000e-06    -3.760000e-06   171.595550          0.001130   
4     1.050000e-05    -1.050000e-05   172.979370          0.001900   

   koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0         -0.003520  ...             -81      4.467           0.064   
1         -0.000581  ...            -176      4.544           0.044   
2         -0.000115  ...            -174      4.564           0.053   
3         -0.001130  ...            -211      4.438           0.070   
4         -0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 39 columns]

# Create a Train Test Split

Use `koi_disposition` for the y values

In [6]:
y = df["koi_disposition"]
X = selected_features

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [8]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
6080              1              0              0              0   12.496435   
3001              0              0              0              0   11.615625   
570               0              1              0              0   10.980246   
4897              1              0              0              0  466.908240   
625               0              1              1              1    1.061933   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
6080     2.213000e-04    -2.213000e-04   132.035800          0.014300   
3001     1.528000e-04    -1.528000e-04   131.968430          0.008230   
570      6.930000e-07    -6.930000e-07   137.137607          0.000053   
4897     1.194000e-02    -1.194000e-02   136.373100          0.019000   
625      1.250000e-06    -1.250000e-06   133.850441          0.000978   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
6080         -0.014300  ...            -286      3.805           0.390   
3001         -0.008230  ...             -72      4.083           0.368   
570          -0.000053  ...            -159      4.462           0.098   
4897         -0.019000  ...            -146      4.456           0.102   
625          -0.000978  ...            -167      3.975           0.259   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
6080          -0.130     2.730          0.535         -1.248  289.23080   
3001          -0.092     1.453          0.218         -0.510  293.52756   
570           -0.182     0.897          0.238         -0.119  282.79764   
4897          -0.361     0.867          0.448         -0.103  297.65436   
625           -0.111     1.851          0.383         -0.575  288.90253   

            dec  koi_kepmag  
6080  44.412483      13.054  
3001  41.111439      15.162  
570   43.578129      14.212  
4897  43.178551      15.202  
625   44.632992      12.953  

[5 rows x 39 columns]

In [9]:
X_test.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
2106              0              0              0              0   14.591504   
2841              0              0              1              0    1.284992   
3377              0              1              1              0   55.700264   
5092              1              0              1              1   12.425571   
47                0              0              0              0   40.419504   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
2106         0.000009        -0.000009   180.851546           0.00048   
2841         0.000007        -0.000007   132.740870           0.00526   
3377         0.000972        -0.000972   152.695700           0.01300   
5092         0.000600        -0.000600   141.529800           0.04800   
47           0.000114        -0.000114   173.564690           0.00222   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
2106          -0.00048  ...            -178      4.199           0.246   
2841          -0.00526  ...            -180      3.852           0.315   
3377          -0.01300  ...            -138      4.608           0.049   
5092          -0.04800  ...            -155      4.564           0.040   
47            -0.00222  ...            -163      4.507           0.116   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
2106          -0.164     1.312          0.355         -0.355  288.75781   
2841          -0.105     2.106          0.392         -0.729  298.94785   
3377          -0.018     0.670          0.033         -0.058  295.95798   
5092          -0.160     0.827          0.199         -0.066  297.74551   
47            -0.105     0.781          0.116         -0.095  294.31686   

            dec  koi_kepmag  
2106  39.350571      13.311  
2841  43.539711      12.923  
3377  49.041012      14.807  
5092  40.674290      14.961  
47    50.080231      15.487  

[5 rows x 39 columns]

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [10]:
# Scale your data
# Import dependencies
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

C:\Users\tonju\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\tonju\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\tonju\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\tonju\anaconda3\envs\PythonData\lib\site-packages

In [11]:
# scale data
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
X_test_scaled

array([[0.        , 0.        , 0.        , ..., 0.40734311, 0.1706394 ,
        0.52442351],
       [0.        , 0.        , 1.        , ..., 0.87363927, 0.43819352,
        0.49235474],
       [0.        , 1.        , 1.        , ..., 0.73682284, 0.7895534 ,
        0.64807009],
       ...,
       [0.        , 1.        , 0.        , ..., 0.63866399, 0.34296551,
        0.51599306],
       [1.        , 0.        , 0.        , ..., 0.7545887 , 0.87576164,
        0.67798992],
       [0.        , 0.        , 0.        , ..., 0.6811828 , 0.43800958,
        0.55798   ]])

In [13]:
# Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

print(encoded_y_test)

[0 2 2 ... 2 2 1]


# Train the Model



In [14]:
# creating a RF classifier
clf = RandomForestClassifier(n_estimators = 100)  

In [15]:
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train_scaled, encoded_y_train)
predictions = clf.predict(X_test_scaled)
predictions

array([0, 2, 2, ..., 2, 2, 1])

In [17]:
print(f"Training Data Score: {clf.score(X_train_scaled, encoded_y_train)}")
print(f"Testing Data Score: {clf.score(X_test_scaled, encoded_y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8975972540045767


# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [25]:
print(clf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}


In [29]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {"classifier__max_depth": [3, None],
              "classifier__max_features": [1, 3, 10],
              "classifier__min_samples_split": [1, 3, 10],
              "classifier__min_samples_leaf": [1, 3, 10],
              # "bootstrap": [True, False],
              "classifier__criterion": ["gini", "entropy"]}
grid3 = GridSearchCV(clf, param_grid, verbose=3)

In [30]:
# Train the model with GridSearch
grid3.fit(X_train_scaled, encoded_y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV] classifier__criterion=gini, classifier__max_depth=3, classifier__max_features=1, classifier__min_samples_leaf=1, classifier__min_samples_split=1 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


ValueError: Invalid parameter classifier for estimator RandomForestClassifier(). Check the list of available parameters with `estimator.get_params().keys()`.

In [ ]:
print(grid3.best_params_)
print(grid3.best_score_)

# Save the Model

In [ ]:
!pip install joblib

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'Anthony_Njuguna.sav'
joblib.dump(model, filename)